import type { Project } from "@/lib/types/project"

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-001",
    name: "Google Workspace 全社導入支援",
    client: "A社（製造業・5,000名）",
    mainAssignee: "今井",
    subAssignee: "金山",
    presalesTemplateId: "ps-standard",
    fdeTemplateId: "",
    priority: "高",
    status: "active",
    description: "Google Workspace の全社 5,000 ライセンス導入。移行計画・トレーニングを含む。",
    createdAt: "2026-03-15",
    milestones: [
      { id: "ps-hearing",        label: "初期ヒアリング",              track: "presales", date: "2026-03-20", completed: true,  isReview: false },
      { id: "ps-draft",          label: "提案書作成",                  track: "presales", date: "2026-04-02", completed: true,  isReview: false },
      { id: "ps-kojima",         label: "小島Dir レビュー",            track: "presales", date: "2026-04-08", completed: false, isReview: true, reviewer: "小島Dir" },
      { id: "ps-nishizawa",      label: "西澤さん レビュー",           track: "presales", date: "2026-04-14", completed: false, isReview: true, reviewer: "西澤さん" },
      { id: "ps-cr",             label: "CR レビュー",                 track: "presales", date: "2026-04-18", completed: false, isReview: true, reviewer: "CR" },
      { id: "ps-pre-proposal",   label: "プレ提案（クライアント）",     track: "presales", date: "2026-04-25", completed: false, isReview: true, reviewer: "クライアント" },
      { id: "ps-final-proposal", label: "本提案（クライアント）",       track: "presales", date: "2026-05-09", completed: false, isReview: true, reviewer: "クライアント" },
    ],
  },
  {
    id: "proj-002",
    name: "BigQuery データ基盤構築",
    client: "B社（金融・DWH移行）",
    mainAssignee: "秋武",
    subAssignee: "今井",
    presalesTemplateId: "ps-standard",
    fdeTemplateId: "fde-standard",
    priority: "高",
    status: "active",
    description: "オンプレDWHからBigQueryへの移行。リアルタイム分析パイプライン構築。",
    createdAt: "2026-03-20",
    milestones: [
      { id: "ps-hearing",        label: "初期ヒアリング",              track: "presales", date: "2026-03-25", completed: true,  isReview: false },
      { id: "ps-draft",          label: "提案書作成",                  track: "presales", date: "2026-04-12", completed: false, isReview: false },
      { id: "ps-kojima",         label: "小島Dir レビュー",            track: "presales", date: "2026-04-18", completed: false, isReview: true, reviewer: "小島Dir" },
      { id: "ps-nishizawa",      label: "西澤さん レビュー",           track: "presales", date: "2026-04-24", completed: false, isReview: true, reviewer: "西澤さん" },
      { id: "ps-cr",             label: "CR レビュー",                 track: "presales", date: "2026-04-28", completed: false, isReview: true, reviewer: "CR" },
      { id: "ps-pre-proposal",   label: "プレ提案（クライアント）",     track: "presales", date: "",           completed: false, isReview: true, reviewer: "クライアント" },
      { id: "ps-final-proposal", label: "本提案（クライアント）",       track: "presales", date: "",           completed: false, isReview: true, reviewer: "クライアント" },
      { id: "fde-requirements",  label: "要件定義",                    track: "fde",      date: "2026-04-01", completed: true,  isReview: false },
      { id: "fde-arch",          label: "アーキテクチャ設計",          track: "fde",      date: "2026-04-10", completed: false, isReview: false },
      { id: "fde-poc",           label: "PoC 実施",                    track: "fde",      date: "2026-04-20", completed: false, isReview: false },
      { id: "fde-report",        label: "結果報告書作成",               track: "fde",      date: "2026-04-28", completed: false, isReview: false },
      { id: "fde-integrate",     label: "提案書反映完了",               track: "fde",      date: "2026-05-02", completed: false, isReview: true, reviewer: "小島Dir" },
    ],
  },
  {
    id: "proj-003",
    name: "Cloud Run マイクロサービス移行",
    client: "C社（EC・コンテナ化）",
    mainAssignee: "秋武",
    subAssignee: "",
    presalesTemplateId: "ps-fast",
    fdeTemplateId: "fde-light",
    priority: "中",
    status: "active",
    description: "モノリシックアプリのCloud Runへのコンテナ化移行提案。",
    createdAt: "2026-03-25",
    milestones: [
      { id: "ps-hearing",          label: "初期ヒアリング",            track: "presales", date: "2026-03-28", completed: true,  isReview: false },
      { id: "ps-draft",            label: "提案書作成",                track: "presales", date: "2026-04-05", completed: true,  isReview: false },
      { id: "ps-kojima-nishizawa", label: "小島Dir + 西澤さん 合同",   track: "presales", date: "2026-04-14", completed: false, isReview: true, reviewer: "小島Dir" },
      { id: "ps-cr",               label: "CR レビュー",               track: "presales", date: "2026-04-18", completed: false, isReview: true, reviewer: "CR" },
      { id: "ps-final-proposal",   label: "本提案（クライアント）",     track: "presales", date: "2026-04-28", completed: false, isReview: true, reviewer: "クライアント" },
      { id: "fde-research",        label: "技術調査",                  track: "fde",      date: "2026-04-01", completed: true,  isReview: false },
      { id: "fde-poc",             label: "PoC / 検証",                track: "fde",      date: "2026-04-10", completed: false, isReview: false },
      { id: "fde-report",          label: "結果報告",                  track: "fde",      date: "2026-04-14", completed: false, isReview: false },
    ],
  },
  {
    id: "proj-004",
    name: "Vertex AI 需要予測PoC",
    client: "D社（小売・在庫最適化）",
    mainAssignee: "金山",
    subAssignee: "秋武",
    presalesTemplateId: "ps-light",
    fdeTemplateId: "fde-standard",
    priority: "中",
    status: "active",
    description: "在庫最適化のためのVertex AI活用 PoC。3ヶ月での実証実験。",
    createdAt: "2026-04-01",
    milestones: [
      { id: "ps-hearing",        label: "ヒアリング",                  track: "presales", date: "2026-04-07", completed: false, isReview: false },
      { id: "ps-draft",          label: "提案書作成",                  track: "presales", date: "2026-04-18", completed: false, isReview: false },
      { id: "ps-final-proposal", label: "提案実施",                    track: "presales", date: "2026-05-02", completed: false, isReview: true, reviewer: "クライアント" },
      { id: "fde-requirements",  label: "要件定義",                    track: "fde",      date: "2026-04-10", completed: false, isReview: false },
      { id: "fde-arch",          label: "アーキテクチャ設計",          track: "fde",      date: "2026-04-18", completed: false, isReview: false },
      { id: "fde-poc",           label: "PoC 実施",                    track: "fde",      date: "2026-04-28", completed: false, isReview: false },
      { id: "fde-report",        label: "結果報告書作成",               track: "fde",      date: "2026-05-05", completed: false, isReview: false },
      { id: "fde-integrate",     label: "提案書反映完了",               track: "fde",      date: "2026-05-09", completed: false, isReview: true, reviewer: "小島Dir" },
    ],
  },
  {
    id: "proj-005",
    name: "Google Meet HW 全社展開",
    client: "E社（不動産・30室）",
    mainAssignee: "金山",
    subAssignee: "",
    presalesTemplateId: "ps-light",
    fdeTemplateId: "",
    priority: "低",
    status: "won",
    description: "全会議室へのGoogle Meet ハードウェア一括導入。30室対応。",
    createdAt: "2026-03-10",
    milestones: [
      { id: "ps-hearing",        label: "ヒアリング",                  track: "presales", date: "2026-03-12", completed: true,  isReview: false },
      { id: "ps-draft",          label: "提案書作成",                  track: "presales", date: "2026-03-20", completed: true,  isReview: false },
      { id: "ps-final-proposal", label: "提案実施",                    track: "presales", date: "2026-03-28", completed: true,  isReview: true, reviewer: "クライアント" },
    ],
  },
]
